
from PyQt5 import QtGui, QtWidgets, QtCore
from tool_func import func

class Ui_MainWindow(func):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 282)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.infobutton = QtWidgets.QPushButton(self.tab1)
        self.infobutton.setGeometry(QtCore.QRect(40, 120, 101, 31))
        self.infobutton.setStyleSheet("")
        self.infobutton.setObjectName("infobutton")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(40, 60, 111, 21))
        self.label.setObjectName("label")
        self.maintext = QtWidgets.QLabel(self.tab1)
        self.maintext.setGeometry(QtCore.QRect(30, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.maintext.setFont(font)
        self.maintext.setScaledContents(False)
        self.maintext.setAlignment(QtCore.Qt.AlignCenter)
        self.maintext.setWordWrap(False)
        self.maintext.setObjectName("maintext")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.coin_price_combo = QtWidgets.QComboBox(self.tab1)
        self.coin_price_combo.setGeometry(QtCore.QRect(40, 90, 104, 26))
        self.coin_price_combo.setEditable(True)
        self.coin_price_combo.setMaxVisibleItems(50)
        self.coin_price_combo.setObjectName("coin_price_combo")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.input_coin_trade = QtWidgets.QLineEdit(self.tab2)
        self.input_coin_trade.setGeometry(QtCore.QRect(60, 90, 121, 16))
        self.input_coin_trade.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.input_coin_trade.setInputMask("")
        self.input_coin_trade.setText("")
        self.input_coin_trade.setMaxLength(8)
        self.input_coin_trade.setDragEnabled(False)
        self.input_coin_trade.setReadOnly(False)
        self.input_coin_trade.setClearButtonEnabled(False)
        self.input_coin_trade.setObjectName("input_coin_trade")
        self.example_trade = QtWidgets.QLabel(self.tab2)
        self.example_trade.setGeometry(QtCore.QRect(50, 60, 111, 21))
        self.example_trade.setObjectName("example_trade")
        self.trade_button_trade = QtWidgets.QPushButton(self.tab2)
        self.trade_button_trade.setGeometry(QtCore.QRect(80, 150, 81, 31))
        self.trade_button_trade.setStyleSheet("")
        self.trade_button_trade.setObjectName("trade_button_trade")
        self.coin_price_trade = QtWidgets.QLabel(self.tab2)
        self.coin_price_trade.setGeometry(QtCore.QRect(210, 60, 161, 31))
        self.coin_price_trade.setText("")
        self.coin_price_trade.setObjectName("coin_price_trade")
        self.result_trade = QtWidgets.QLabel(self.tab2)
        self.result_trade.setGeometry(QtCore.QRect(210, 120, 161, 31))
        self.result_trade.setText("")
        self.result_trade.setObjectName("result_trade")
        self.input_coin_count_trade = QtWidgets.QLineEdit(self.tab2)
        self.input_coin_count_trade.setGeometry(QtCore.QRect(60, 120, 121, 16))
        self.input_coin_count_trade.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.input_coin_count_trade.setInputMask("")
        self.input_coin_count_trade.setText("")
        self.input_coin_count_trade.setMaxLength(8)
        self.input_coin_count_trade.setDragEnabled(False)
        self.input_coin_count_trade.setReadOnly(False)
        self.input_coin_count_trade.setClearButtonEnabled(False)
        self.input_coin_count_trade.setObjectName("input_coin_count_trade")
        self.label_3 = QtWidgets.QLabel(self.tab2)
        self.label_3.setGeometry(QtCore.QRect(0, 120, 57, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab2)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 41, 20))
        self.label_4.setObjectName("label_4")
        self.maintext_2 = QtWidgets.QLabel(self.tab2)
        self.maintext_2.setGeometry(QtCore.QRect(40, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.maintext_2.setFont(font)
        self.maintext_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.maintext_2.setScaledContents(False)
        self.maintext_2.setAlignment(QtCore.Qt.AlignCenter)
        self.maintext_2.setWordWrap(False)
        self.maintext_2.setObjectName("maintext_2")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.input_api_key_settings = QtWidgets.QLineEdit(self.tab3)
        self.input_api_key_settings.setGeometry(QtCore.QRect(110, 30, 251, 21))
        self.input_api_key_settings.setObjectName("input_api_key_settings")
        self.api_key_settings = QtWidgets.QLabel(self.tab3)
        self.api_key_settings.setGeometry(QtCore.QRect(50, 30, 57, 16))
        self.api_key_settings.setObjectName("api_key_settings")
        self.api_secret_key_settings = QtWidgets.QLabel(self.tab3)
        self.api_secret_key_settings.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.api_secret_key_settings.setObjectName("api_secret_key_settings")
        self.input_api_secret_key_settings = QtWidgets.QLineEdit(self.tab3)
        self.input_api_secret_key_settings.setGeometry(QtCore.QRect(110, 60, 251, 21))
        self.input_api_secret_key_settings.setObjectName("input_api_secret_key_settings")
        self.configure_button_settings = QtWidgets.QPushButton(self.tab3)
        self.configure_button_settings.setGeometry(QtCore.QRect(110, 90, 121, 32))
        self.configure_button_settings.setObjectName("configure_button_settings")
        self.reset_button_settings = QtWidgets.QPushButton(self.tab3)
        self.reset_button_settings.setGeometry(QtCore.QRect(240, 90, 121, 32))
        self.reset_button_settings.setObjectName("reset_button_settings")
        self.label_settings = QtWidgets.QLabel(self.tab3)
        self.label_settings.setGeometry(QtCore.QRect(70, 160, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_settings.setFont(font)
        self.label_settings.setText("")
        self.label_settings.setObjectName("label_settings")
        self.tabWidget.addTab(self.tab3, "")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.infobutton.clicked.connect(self.info_price)
        self.trade_button_trade.clicked.connect(self.coin_price_trade.clear)
        # self.coin_price_combo.currentIndexChanged.connect(self.coin_price_reflesh_)
        self.start_func()
        self.control()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Binance Bot"))
        self.infobutton.setText(_translate("MainWindow", "Coin Price"))
        self.label.setText(_translate("MainWindow", "Example: HOTBTC"))
        self.maintext.setText(_translate("MainWindow", "Binance Bot"))
        self.coin_price_combo.setCurrentText(_translate("MainWindow", "Select Coin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Coin Price"))
        self.example_trade.setText(_translate("MainWindow", "Example: HOTBTC"))
        self.trade_button_trade.setText(_translate("MainWindow", "Trade"))
        self.label_3.setText(_translate("MainWindow", "Amount :"))
        self.label_4.setText(_translate("MainWindow", "Coin :"))
        self.maintext_2.setText(_translate("MainWindow", "Market Buy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Trade"))
        self.api_key_settings.setText(_translate("MainWindow", "API Key :"))
        self.api_secret_key_settings.setText(_translate("MainWindow", "API Secret Key :"))
        self.configure_button_settings.setText(_translate("MainWindow", "Configure"))
        self.reset_button_settings.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Settings"))
